// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beaajyjkdsmamzejqkeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlYWFqeWprZHNtYW16ZWpxa2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTI2ODksImV4cCI6MjA2MDIyODY4OX0.ttOmOVs0IO0DtbaKKCbKHmNuqzhtEOMITeWMPbB_gXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);